export enum ShipmentStatus {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  PICKED = "PICKED",
  IN_TRANSIT = "IN_TRANSIT",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
  RETURNED = "RETURNED",
}
